[versions]
#secrets-gradle = "2.0.1"
accompanist = "0.32.0"
activityCompose = "1.11.0"
agp = "8.13.2"
androidxRulesVersion = "1.5.0"
cameraX = "1.5.1"
coil = "3.0.4"
composeBom = "2025.11.00"
coreKtx = "1.17.0"
crashlytics = "3.0.6"
credentials = "1.5.0"
cucumber = "7.18.1" # do not update to last release as some libraries will not work at last release.
datastorePreferences = "1.1.7"
espressoCore = "3.5.0"
firebase = "34.6.0"
googleid = "1.1.1"
googlemapsAndroid = "2.13.0"
googlemapsSdk = "19.2.0"
googleservices = "4.4.4"
hilt = "2.57.2"
hiltNavigationCompose = "1.3.0"
junit = "4.13.2"
junitVersion = "1.1.5"
kotlin = "2.2.21"
kotlinxCoroutinesTest = "1.9.0"
ksp = "2.2.20-2.0.3"
lifecycleRuntimeKtx = "2.9.4"
materialIconsExtended = "1.7.8"
mockitoKotlin = "5.4.0"
oliviermarteaux = "6.1.0"
mockkVersion = "1.13.5"

[libraries]
androidx-activity-compose = { group = "androidx.activity", name = "activity-compose", version.ref = "activityCompose" }
androidx-camera-camera2 = { group = "androidx.camera", name = "camera-camera2", version.ref = "cameraX" }
androidx-camera-core = { group = "androidx.camera", name = "camera-core", version.ref = "cameraX" }
androidx-camera-lifecycle = { group = "androidx.camera", name = "camera-lifecycle", version.ref = "cameraX" }
androidx-camera-view = { group = "androidx.camera", name = "camera-view", version.ref = "cameraX" }
androidx-compose-bom = { group = "androidx.compose", name = "compose-bom", version.ref = "composeBom" }
androidx-compose-material3 = { group = "androidx.compose.material3", name = "material3" }
androidx-compose-ui = { group = "androidx.compose.ui", name = "ui" }
androidx-compose-ui-graphics = { group = "androidx.compose.ui", name = "ui-graphics" }
androidx-compose-ui-test-junit4 = { group = "androidx.compose.ui", name = "ui-test-junit4" }
androidx-compose-ui-test-manifest = { group = "androidx.compose.ui", name = "ui-test-manifest" }
androidx-compose-ui-tooling = { group = "androidx.compose.ui", name = "ui-tooling" }
androidx-compose-ui-tooling-preview = { group = "androidx.compose.ui", name = "ui-tooling-preview" }
androidx-core-ktx = { group = "androidx.core", name = "core-ktx", version.ref = "coreKtx" }
androidx-credentials = {module = "androidx.credentials:credentials", version.ref = "credentials"}
androidx-espresso-core = { group = "androidx.test.espresso", name = "espresso-core", version.ref = "espressoCore" }
androidx-junit = { group = "androidx.test.ext", name = "junit", version.ref = "junitVersion" }
androidx-lifecycle-runtime-ktx = { group = "androidx.lifecycle", name = "lifecycle-runtime-ktx", version.ref = "lifecycleRuntimeKtx" }
androidx-navigation-compose = { module = "androidx.navigation:navigation-compose" }
androidx-test-rules = { module = "androidx.test:rules", version.ref = "androidxRulesVersion" }
coil-compose = { module = "io.coil-kt.coil3:coil-compose", version.ref = "coil" }
coil-network-okhttp = { module = "io.coil-kt.coil3:coil-network-okhttp", version.ref = "coil" }
cucumber-android = { module = "io.cucumber:cucumber-android", version.ref = "cucumber" }
cucumber-java = { module = "io.cucumber:cucumber-java", version.ref = "cucumber" }
cucumber-junit = { module = "io.cucumber:cucumber-junit", version.ref = "cucumber" }
cucumber-messages = { module = "io.cucumber:messages", version.ref = "cucumber" }
cucumber-picocontainer = { module = "io.cucumber:cucumber-picocontainer", version.ref = "cucumber" }
datastore-preferences = { module = "androidx.datastore:datastore-preferences", version.ref = "datastorePreferences" }
firebase-analytics = { group = "com.google.firebase", name = "firebase-analytics" }
firebase-appcheck-playintegrity = { module = "com.google.firebase:firebase-appcheck-playintegrity" }
firebase-auth = { module = "com.google.firebase:firebase-auth" }
firebase-bom = { group = "com.google.firebase", name = "firebase-bom", version.ref = "firebase" }
firebase-crashlytics-ndk = { module = "com.google.firebase:firebase-crashlytics-ndk" }
firebase-firestore = { module = "com.google.firebase:firebase-firestore" }
firebase-messaging = { module = "com.google.firebase:firebase-messaging" }
firebase-storage = { module = "com.google.firebase:firebase-storage" }
google-accompanist = { module = "com.google.accompanist:accompanist-permissions", version.ref = "accompanist"}
googleid = { module = "com.google.android.libraries.identity.googleid:googleid", version.ref = "googleid" }
googlemaps-android = {module = "com.google.maps.android:maps-compose", version.ref = "googlemapsAndroid"}
googlemaps-sdk = {module = "com.google.android.gms:play-services-maps", version.ref = "googlemapsSdk"}
hilt = { group = "com.google.dagger", name = "hilt-android", version.ref = "hilt" }
hilt-compiler = { group = "com.google.dagger", name = "hilt-compiler", version.ref = "hilt" }
hilt-navigation-compose = { module = "androidx.hilt:hilt-navigation-compose", version.ref = "hiltNavigationCompose" }
hilt-testing = {group = "com.google.dagger", name = "hilt-android-testing", version.ref = "hilt"}
junit = { group = "junit", name = "junit", version.ref = "junit" }
kotlinx-coroutines-test = { group = "org.jetbrains.kotlinx", name ="kotlinx-coroutines-test", version.ref = "kotlinxCoroutinesTest" }
material-icons-extended = { module = "androidx.compose.material:material-icons-extended", version.ref = "materialIconsExtended" }
mockito-kotlin = { module = "org.mockito.kotlin:mockito-kotlin", version.ref = "mockitoKotlin" }
oliviermarteaux-compose = { module = "com.github.OlivierMarteaux.shared-android-library:compose", version.ref = "oliviermarteaux" }
oliviermarteaux-core = { module = "com.github.OlivierMarteaux.shared-android-library:core", version.ref = "oliviermarteaux" }
oliviermarteaux-test = { module = "com.github.OlivierMarteaux.shared-android-library:test", version.ref = "oliviermarteaux" }
play-services-credentials = {module = "androidx.credentials:credentials-play-services-auth", version.ref = "credentials"}
mockk = { module = "io.mockk:mockk", version.ref = "mockkVersion" }

[plugins]
#secrets-gradle = { id = "com.google.android.libraries.mapsplatform.secrets-gradle-plugin", version.ref = "secrets-gradle"}
android-application = { id = "com.android.application", version.ref = "agp" }
crashlytics = { id = "com.google.firebase.crashlytics", version.ref = "crashlytics" }
googleservices = { id = "com.google.gms.google-services", version.ref = "googleservices" }
hilt = { id = "com.google.dagger.hilt.android", version.ref = "hilt" }
kotlin-android = { id = "org.jetbrains.kotlin.android", version.ref = "kotlin" }
kotlin-compose = { id = "org.jetbrains.kotlin.plugin.compose", version.ref = "kotlin" }
ksp = { id = "com.google.devtools.ksp", version.ref = "ksp" }